version: 1
metadata:
  access_right: open
  license: CC-BY-4.0
  publication_type: article
  upload_type: publication
pipelines:
  buildEnv:
    envs:
      host:
        args: []
    path: scripts/buildEnv
    stages:
    - install-sciunit.sh
  refreshData:
    envs:
      host:
        args: []
    path: scripts/refreshData
    stages:
    - run.sh
  executeModel:
    envs:
      host:
        args: []
    path: scripts/executeModel
    stages:
    - setup.sh
    - run.sh
    - evaluate.sh
    - archive.sh
  repeatPreprocess:
    envs:
      host:
        args: []
    path: scripts/repeat
    stages:
    - setup.sh
  repeatModel:
    envs:
      host:
        args: []
    path: scripts/repeat
    stages:
    - run.sh
  repeatEvaluation:
    envs:
      host:
        args: []
    path: scripts/repeat
    stages:
    - evaluate.sh
popperized:
- popperized
badge-server-url: http://badges.falsifiable.us
